using UnityEngine;

public class Bullet : MonoBehaviour
{
    [HideInInspector] public float attackDamage;
    [HideInInspector] public Weapon owner; // üëà ‡πÄ‡∏û‡∏¥‡πà‡∏°‡∏ï‡∏±‡∏ß‡πÅ‡∏õ‡∏£‡πÑ‡∏ß‡πâ‡πÄ‡∏Å‡πá‡∏ö‡πÄ‡∏à‡πâ‡∏≤‡∏Ç‡∏≠‡∏á‡∏Å‡∏£‡∏∞‡∏™‡∏∏‡∏ô

    void OnTriggerEnter(Collider other)
    {
        if (other.TryGetComponent<Enemy>(out Enemy enemy))
        {
            enemy.TakeDamage(attackDamage);

            // üëá ‡∏ö‡∏≠‡∏Å Enemy ‡∏ß‡πà‡∏≤‡πÇ‡∏î‡∏ô‡∏¢‡∏¥‡∏á‡∏à‡∏≤‡∏Å‡πÉ‡∏Ñ‡∏£
            if (owner != null)
                enemy.OnAttackedBy(owner.transform);

            Destroy(gameObject);
        }
    }
}
